Django/django_ws_9_a/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

Django/django_ws_9_a/diaries/urls.py
from django.urls import path
from . import views


app_name = 'diaries'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
]

Django/django_ws_9_a/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/django_ws_9_a/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
    path('<int:todo_pk>/update/', views.update, name='update'),
]

Django/django_ws_9_a/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

Django/django_ws_9_a/diaries/models.py
from django.db import models

# Create your models here.
class Diary(models.Model):
    content = models.CharField(max_length=125)
    picture = models.ImageField(blank=True, upload_to='diary/%y/%b/%a')
    created_at = models.DateTimeField(auto_now_add=True)

Django/django_ws_9_a/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

Django/django_ws_9_a/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=12)
#     password = forms.CharField(widget=forms.PasswordInput())

Django/django_ws_9_a/diaries/forms.py
from django import forms
from .models import Diary


class DiaryForm(forms.ModelForm):

    class Meta:
        model = Diary
        fields = '__all__'

Django/django_ws_9_a/todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = '__all__'
        # exclude = ('is_completed', )
        widgets = {'is_completed': forms.HiddenInput()}

Django/django_ws_9_a/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
# from .forms import LoginForm

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('todos:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

Django/django_ws_9_a/diaries/views.py
from django.shortcuts import render, redirect
from .models import Diary
from .forms import DiaryForm

# Create your views here.
def index(request):
    diaries = Diary.objects.all()
    context = {
        'diaries': diaries,
    }
    return render(request, 'diaries/index.html', context)

def create(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('diaries:index')
    else:
        form = DiaryForm()
    context = {
        'form': form
    }
    return render(request, 'diaries/create.html', context)

Django/django_ws_9_a/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm

# Create your views here.
def index(request):
    print(request.user.is_authenticated)
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

def create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save()
            return redirect('todos:detail', todo.pk)
    else:
        form = TodoForm()
    context = {
        'form': form
    }
    return render(request, 'todos/create.html', context)
    
def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)


def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    if request.method == 'POST':
        todo.delete()
        return redirect('todos:index')
    else:
        return redirect('todos:detail', todo.pk)

def update(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            todo = form.save()
            return redirect('todos:detail', todo.pk)
    else:
        form = TodoForm(instance=todo)
    context = {
        'todo': todo,
        'form': form
    }
    return render(request, 'todos/update.html', context)

Django/django_ws_9_a/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>로그인 페이지</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

Django/django_ws_9_a/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<h1>회원 가입 페이지</h1>
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="회원가입">
    
</form>

{% endblock content %}

Django/django_ws_9_a/diaries/templates/diaries/create.html
{% extends "base.html" %}

{% block content %}
  <h1>일기 작성 페이지</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="작성">
  </form>
{% endblock content %}

Django/django_ws_9_a/diaries/templates/diaries/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <h1>일기장</h1>
  <a href="{% url "diaries:create" %}">[일기 쓰기]</a>
  <ul>
    {% for diary in diaries %}
      <li>
        <p>작성일 : {{ diary.created_at }}</p>
        {% if diary.picture %}
          <img src="{{ diary.picture.url }}" alt="{{ diary.picture }}">
        {% else %}
          <img src="{% static "diaries/default.png" %}" alt="{{ diary.picture }}">
        {% endif %}
        <p>{{ diary.content }}</p>
      </li>
    <hr>
    {% empty %}
      <li>아직 작성한 일기가 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}

Django/django_ws_9_a/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>할 일 목록 관리 프로젝트</title>
</head>
<body>
  <a href="{% url "todos:index" %}"><img src="{% static "logo.png" %}" alt="logo" width="30px" height="30px;"></a> | 
  <a href="{% url "todos:create" %}">[CREATE]</a>
  <a href="{% url "accounts:login" %}">[LOGIN]</a>
  <a href="{% url "accounts:signup" %}">[Sign up]</a>
  <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="[LOGOUT]">
  </form>
  <h3>Hello, {{ user.username }}</h3>
  <a href="{% url "diaries:index" %}">[DIARY]</a>
  {% block content %}
  {% endblock content %}
</body>
</html>

Django/django_ws_9_a/todos/templates/todos/create.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form action="{% url "todos:create" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}

Django/django_ws_9_a/todos/templates/todos/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 상세 페이지</h1>
  <hr>
  <p>{{ todo.pk }}번 째 할 일</p>
  <p>할 일 : {{ todo.work }}</p>
  <p>내 용 : {{ todo.content }}</p>
  <p>일 자 : {{ todo.created_at }}</p>
  <p>완 료 : {{ todo.is_completed }}</p>
  <hr>
  <a href="{% url "todos:update" todo.pk %}">수정</a>
  <form action="{% url "todos:delete" todo.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
{% endblock content %}

Django/django_ws_9_a/todos/templates/todos/index.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 관리 프로젝트 메인 페이지</h1>
  <p>이 곳에서 할 일 목록을 관리합니다.</p>
  <ul>
    {% for todo in todo_list %}
      <li>
        <input type="checkbox" value="{{ todo.is_completed }}" {% if todo.is_completed %}checked{% endif %}>
        <a href="{% url "todos:detail" todo.pk %}">{{ todo.work }}</a>
      </li>
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}

Django/django_ws_9_a/todos/templates/todos/update.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}