Django/minsoo_homepage/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),

]

Django/minsoo_homepage/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),

]

Django/minsoo_homepage/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django/minsoo_homepage/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    name = models.CharField(max_length = 10)
    content = models.TextField()

Django/minsoo_homepage/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User

# Create your views here.
def index(request):
    accounts = User.objects.all()
    context = {
        'accounts' : accounts
    }
    return render(request, 'accounts/index.html', context)


def login(request):
    if request.method =='POST':
        # 받아들이는 method가 POST일 때,
        # 인증하는 form인 AUthenticationForm사용
        form = AuthenticationForm(request, request.POST)
        # 만약 폼이 타당하다면, 로그인
        # 로그인 한 후에는 main페이지로 이동
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        # GET METHOD라면, login홈페이지로 이동해서
        # 로그인 하도록 시키기
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

Django/minsoo_homepage/articles/views.py
from django.shortcuts import render
from .models import Article
# Create your views here.
def index(request):
    article = Article.objects.all()
    context = {
        'article' : article,
    }
    return render(request, 'articles/index.html', context)

Django/minsoo_homepage/accounts/templates/accounts/index.html
{% extends "base.html" %}
{% block content %}

<h1>구미 3반 알(고리즘)쓰(터디)</h1>
<h2>Hello, {{user.username}} 님! </h2>
<a href="{% url "accounts:login" %}">[LOGIN]</a>
<form action="{% url "accounts:logout" %}" method='POST'>
{% csrf_token %}
<input type="submit" value="LOGOUT">

</form>
<h1>전체 스터디원 목록</h1>
{% for account in accounts %}
<ul>
  <li>
    {{account.username}}
    <hr>
    
</li>
</ul>
{% endfor %}
{% endblock content %}

Django/minsoo_homepage/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

<h1>LOGIN PAGE</h1>
{{form.as_p}}
<form action="{% url "accounts:login" %}" method="POST">
{% csrf_token %}
<input type="submit" value="LOGIN">

</form>

{% endblock content %}

Django/minsoo_homepage/articles/templates/articles/index.html
{% extends "base.html" %}
{% block content %}

<h1>알고리즘 스터디의 최종 목표</h1>
<a href="{% url "articles:create" %}">[CREATE]</a>




{% endblock content %}

Django/minsoo_homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block content %}

{% endblock content %}
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>